version: 2.1
executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            # Build the Maven project
            mvn build
            mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
