version: 2.1
executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk  # You can choose a different Java version if needed

jobs:
  build:
    executor: default
    steps:
      - checkout  # This step checks out your code
      - run:
          name: Build and Test
          command: |
            mvn compile  # Compile your Java code
            mvn test     # Run your tests

workflows:
  version: 2
  build:
    jobs:
      - build
  maven_test:
    jobs:
      - maven/test

