version: 2.1
executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk  # You can choose the Java version you need

jobs:
  build:
    executor: default
    steps:
      - checkout  # Pull your source code from your VCS repository
      - run:
          name: Build and Test
          command: |
            # Build the Maven project
            mvn clean install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
